export const ACHIEVEMENT_CODES = {

  FIRST_TASK: "FIRST_TASK",
  TASK_MASTER_25: "TASK_MASTER_25",
  TASK_MASTER_50: "TASK_MASTER_50",
  TASK_MASTER_100: "TASK_MASTER_100",
  TASK_MASTER_250: "TASK_MASTER_250",

  EARLY_BIRD: "EARLY_BIRD",
  NIGHT_OWL: "NIGHT_OWL",
  CONSISTENT_PLANNER: "CONSISTENT_PLANNER",

  FIRST_TOPIC_COMPLETED: "FIRST_TOPIC_COMPLETED",
  TOPIC_MASTER_10: "TOPIC_MASTER_10",
  TOPIC_MASTER_50: "TOPIC_MASTER_50",

  FIRST_MODULE_COMPLETED: "FIRST_MODULE_COMPLETED",
  MODULE_MASTER_5: "MODULE_MASTER_5",
  MODULE_MASTER_10: "MODULE_MASTER_10",

  CN_EXPERT: "CN_EXPERT",
  REVISION_KING: "REVISION_KING",

  FIRST_QUIZ: "FIRST_QUIZ",
  QUIZ_MASTER_10: "QUIZ_MASTER_10",
  QUIZ_MASTER_50: "QUIZ_MASTER_50",
  QUIZ_MASTER_100: "QUIZ_MASTER_100",

  PERFECT_SCORE: "PERFECT_SCORE",
  PERFECT_SCORE_5: "PERFECT_SCORE_5",
  PERFECT_SCORE_25: "PERFECT_SCORE_25",

  SPEED_DEMON: "SPEED_DEMON",
  NO_MISTAKE: "NO_MISTAKE",

  STREAK_3: "STREAK_3",
  STREAK_7: "STREAK_7",
  STREAK_15: "STREAK_15",
  STREAK_30: "STREAK_30",
  STREAK_60: "STREAK_60",
  STREAK_100: "STREAK_100",

  XP_100: "XP_100",
  XP_500: "XP_500",
  XP_1000: "XP_1000",
  XP_5000: "XP_5000",
  XP_10000: "XP_10000",

  LEVEL_2: "LEVEL_2",
  LEVEL_5: "LEVEL_5",
  LEVEL_10: "LEVEL_10",
  LEVEL_20: "LEVEL_20",
  LEVEL_30: "LEVEL_30",
  LEVEL_50: "LEVEL_50",

  WEAK_AREA_CONQUEROR: "WEAK_AREA_CONQUEROR",
  RECOVERY_MASTER: "RECOVERY_MASTER",
  BOUNCED_BACK: "BOUNCED_BACK",

  MIDNIGHT_WARRIOR: "MIDNIGHT_WARRIOR",
  WEEKEND_HUSTLER: "WEEKEND_HUSTLER",
  UNSTOPPABLE: "UNSTOPPABLE",

  LEGEND: "LEGEND",

} as const;