export const XP_REWARDS = {
  TASK_CREATED: 0.5,
  TASK_COMPLETED: 5.0,
  TOPIC_COMPLETED: 15.0,
  MODULE_COMPLETED: 40.0,
  QUIZ_ATTEMPTED: 2.0,
  QUIZ_CORRECT_ANSWER: 3.0,
  QUIZ_PERFECT_SCORE: 30.0,
  REVISION_COMPLETED: 5.0,
  ACHIEVEMENT_UNLOCKED: 0,
} as const;